### ISSUE TITLE
Not getting similar results to your screenshots

### ISSUE THREAD

**Issue by ioogithub** [o0th/tmux-nova#19]
I am trying to use your nord theme. Here is my config:

```
set -g @nova-nerdfonts true
set -g @nova-nerdfonts-left 
set -g @nova-nerdfonts-right 
set -g @nova-segment-mode "#{?client_prefix,Ω,ω}"
set -g @nova-segment-mode-colors "#50fa7b #282a36"
set -g @nova-segment-pomodoro "#(pomodoro status --format ' %%c  %%r %%d') "
set -g @nova-segment-pomodoro-colors "#ff5555 #f8f8f2"
set -g "@nova-pane-active-border-style" "#44475a"
set -g "@nova-pane-border-style" "#282a36"
set -g "@nova-status-style-bg" "#4c566a"
set -g "@nova-status-style-fg" "#d8dee9"
set -g "@nova-status-style-active-bg" "#89c0d0"
set -g "@nova-status-style-active-fg" "#2e3540"
set -g "@nova-status-style-double-bg" "#2d3540"
```
Here are the results.
![Screenshot_20220224_163148](https://user-images.githubusercontent.com/58017942/155611166-233354d7-34a9-4e57-afcd-177d37eb5645.png)

I am using the following:
- tmux-nova installed with tpm
- Konsole Terminal Emulator
- Hack Nerd Font
- tmux 3.0a

I would like to get the arrow effect and the colors right in the status bar but I get an ugly brown and half an arrow. Is this theme compatible with tmux 3.0a? Any idea or something else I can try?

**Comment by o0th** [comment]
Hi @ioogithub, thanks for open an issue! 

In [gallery](https://github.com/o0th/tmux-nova/blob/master/Gallery.md) there's my entire configuration. From what I see from your configuration you're missing `@nova-segments-0-left`, `@nova-segments-0-right`.

```bash
set -g @nova-segments-0-left "mode"
set -g @nova-segments-0-right "pomodoro"
```

With this setting you specify the segments positions. For the colors most likely you need to enable true colors for Konsole.

Currently I'm running on `tmux 3.2_a-1` so I don't think is a version problem.
