### ISSUE TITLE
Can't get modules to work

### ISSUE THREAD

**Issue by z-prince** [o0th/tmux-nova#22]
Sorry to be a nuisance, love your work. I just can't seem to get any of the modules to work on the bar. I'm using MacOs and TPM.
![Screen Shot 2022-04-21 at 22 04 21](https://user-images.githubusercontent.com/65498038/164582011-b640ac05-6b4e-4820-b2ca-28dd1538eb7a.png)
![Screen Shot 2022-04-21 at 22 05 57](https://user-images.githubusercontent.com/65498038/164582121-df40f6b8-b4e8-4008-b6a7-df2093c5b073.png)
.

**Comment by o0th** [comment]
Hi @z-prince, thank you for the appreciation, did you install the plugins like `tmux-cpu`, `tmux-net-speed`?

**Comment by z-prince** [comment]
That was it, thank you so much!
