### ISSUE TITLE
Can't figure out how to get tmux-continuum to work with tmux-nova

### ISSUE THREAD

**Issue by notoyz** [o0th/tmux-nova#34]
[Here](https://github.com/tmux-plugins/tmux-continuum) is the plugin I'm having trouble with.

From their docs:

> Continuous saving
> Tmux environment will be saved at an interval of 15 minutes. All the saving happens in the background without impact to your workflow.
> This action starts automatically when the plugin is installed. **Note it requires the status line to be on to run (since it uses a hook in status-right to run)**.

The suggested method for getting this working is:

```
set -g status-right 'Continuum status: #{continuum_status}'
```
Seeing as I'm using tmux-nova, instead I thought I should do this:

```
set -g @nova-segment-continuum "Continuum status: #{continuum_status}"
```

The segment appears but it reads "Continuum status: off". I assume this is because the "hook in status-right" is not working.

Here are the relevant parts of my config:

```
# Plugins
set -g @plugin 'o0th/tmux-nova' # https://github.com/o0th/tmux-nova
set -g @plugin 'tmux-plugins/tmux-resurrect' # https://github.com/tmux-plugins/tmux-resurrect
set -g @plugin 'tmux-plugins/tmux-continuum' # https://github.com/tmux-plugins/tmux-continuum

# Continuum Segment
set -g @nova-segment-continuum "Continuum status: #{continuum_status}"
set -g @nova-segment-continuum-colors "#303030 #a8a8a8"

# Segment features
set -g @nova-segments-0-left "prefixl session"
set -g @nova-segments-0-right "mode continuum whoami prefixr"

# Resurrect
set -g @resurrect-capture-pane-contents 'on'

# Continuum
set -g @continuum-restore 'on'
set -g @continuum-boot 'on'
```

Any help would be greatly appreciated because I'm stumped!

**Comment by o0th** [comment]
Hi @notoyz! I'm not sure what the expected behavior is for that plugin but we can try something:

```bash
set -g @nova-segment-continuum "Status: #(~/.tmux/plugins/tmux-continuum/scripts/continuum_status.sh)"
```

Then I read [here](https://github.com/tmux-plugins/tmux-continuum/issues/42) that you have to specify `set -g @continuum-save-interval 15` to make it works.

I did these two changes and it seems to be working, let me know if this fixes your issue.
