### ISSUE TITLE
Limited default length of status-left and status-right

### ISSUE THREAD

**Issue by diogoDSN** [o0th/tmux-nova#35]
# Limited default length of status-left and status-right

I wanted to have the following scheme for my status line:
![Screenshot 2024-04-03 at 16 37 38](https://github.com/o0th/tmux-nova/assets/72698868/af6e4cbe-6a67-4612-aa91-6f4c5921b16a)
However, when the session name is larger it overflows its segment. Here the session is called '0123456789':
![Screenshot 2024-04-03 at 16 38 30](https://github.com/o0th/tmux-nova/assets/72698868/6275b1a3-5bb0-44ee-a2fe-3c0a5c4b574f)

After reading the nova scripts I thought that the problem was directly from tmux and found the `status-left-length` option. It seems tmux limits the length of `status-left`, and right, to 10 characters by default. After setting this option to 100 the problem was solved:
![Screenshot 2024-04-03 at 18 32 47](https://github.com/o0th/tmux-nova/assets/72698868/b7a421ea-95a5-4a54-8b78-3603af14b73b)

I think nova should either handle this for the user or at least mention it in the documentation so that the user can customize their theme without having to read the original tmux status line docs.

**Comment by o0th** [comment]
Hi @diogoDSN, thank you for using my plugin and opening an issue! I added a FAQ section in the README that explain and address the issue. I don't want to overwrite these values via tmux-nova to give the user more flexibility.
